metadata:
  name: "mapping-integration-31d8d480"
  labels:
    deploymentUUID: "dd29b71e-3a58-4bd9-a1ee-82139ba63faa"
    integrationName: "mapping-integration-31d8d480"
    integrationRevision: "1"
    integrationUUID: "4fe94ab4-6125-4db0-9fbd-e62d1733c83a"
    logLevel: "INFO"
    dataAnalyzer: "false"
    profileName: "Default"
    profileUUID: "6bb2e3e3-9d2a-4353-837c-05a0a8a5adc6"
spec:
  configuration:
    - type: "property"
      value: "quarkus.log.console.color=true"
    - type: "property"
      value: "quarkus.log.console.level=INFO"
  dependencies: []
  replicas: 1
  resources: []
  sources:
    name: "mapping-integration-31d8d480.groovy"
    content: |
      import org.apache.camel.LoggingLevel

      from('timer:timer?daemon=true&delay=1000&fixedRate=false&period=1000&repeatCount=0').routeId('mapping-integration')
          .setProperty('in-157a8c87-6002-48a7-a20d-de95588e2bd9').constant('{"apiVersion":"camel.apache.org/v1","kind":"Integration"}')
          .setProperty('test-315aac82-fc63-441f-94e7-ae674d4fb382').constant('{"test":"was successfully mapped!"}')
          .log(LoggingLevel.INFO, 'log', 'input json 1: ${exchangeProperty.in-157a8c87-6002-48a7-a20d-de95588e2bd9}; input json 2: ${exchangeProperty.test-315aac82-fc63-441f-94e7-ae674d4fb382}')
          .to('atlasmap:cloud-mapping.adm?allowContextMapAll=false&contentCache=false&lazyStartProducer=false&targetMapMode=MAP')
          .log(LoggingLevel.INFO, 'log', 'output xml: ${body}')
  traits:
    jolokia:
      enabled: true
    logging:
      enabled: true
      level: "DEBUG"
    owner:
      enabled: true
      targetLabels:
        - "jetic.io/data.analyzer"
        - "jetic.io/deployment.uuid"
        - "jetic.io/integration.name"
        - "jetic.io/integration.revision"
        - "jetic.io/integration.uuid"
        - "jetic.io/log.level"
        - "jetic.io/open.api.host"
        - "jetic.io/profile.name"
        - "jetic.io/profile.uuid"
